name: Test toolchain for all examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Test with pytest
        run: |
          python3 -m pytest --html=report.html --self-contained-html
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: report.html